export type TopicKey =
  | "What is ML?"
  | "ML & AI"
  | "ML Languages"
  | "ML JavaScript"
  | "ML Examples"
  | "ML Linear Graphs"
  | "ML Scatter Plots"
  | "ML Perceptrons"
  | "ML Recognition"
  | "ML Training"
  | "ML Testing"
  | "ML Learning"
  | "ML Terminology"
  | "ML Data"
  | "ML Clustering"
  | "ML Regressions"
  | "ML Deep Learning"
  | "ML Brain.js";

export const mlTopics: Record<TopicKey, { heading: string; content: string }> =
  {
    "What is ML?": {
      heading: "What is Machine Learning?",
      content: `
      <div class="space-y-8">
        <div class="bg-gradient-to-r from-blue-500/10 via-purple-500/10 to-pink-500/10 p-8 rounded-2xl backdrop-blur-sm border border-white/10">
          <p class="text-xl text-white/90 leading-relaxed">
            Machine Learning (ML) is a field of Artificial Intelligence (AI) that focuses on developing algorithms that allow computers to learn from and make decisions based on data. Instead of following explicit instructions, a machine can improve its performance over time by identifying patterns and making data-driven predictions.
          </p>
        </div>
        
        <div class="bg-black/50 backdrop-blur-sm border border-white/10 rounded-xl p-8 hover:border-white/20 transition-all duration-300">
          <div class="flex items-center gap-3 mb-6">
            <div class="w-12 h-12 rounded-full bg-blue-500/20 flex items-center justify-center">
              <span class="text-blue-400 text-2xl">🔑</span>
            </div>
            <h2 class="text-2xl font-semibold text-white">Key Components of Machine Learning</h2>
          </div>
          <ul class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <li class="bg-white/5 rounded-lg p-4 hover:bg-white/10 transition-all">
              <h3 class="text-white font-semibold mb-2 flex items-center gap-2">
                <span class="w-2 h-2 bg-blue-500 rounded-full"></span>
                Data
              </h3>
              <p class="text-white/80">The raw information that the machine learns from.</p>
            </li>
            <li class="bg-white/5 rounded-lg p-4 hover:bg-white/10 transition-all">
              <h3 class="text-white font-semibold mb-2 flex items-center gap-2">
                <span class="w-2 h-2 bg-purple-500 rounded-full"></span>
                Model
              </h3>
              <p class="text-white/80">A mathematical representation of a system that the machine uses to make predictions.</p>
            </li>
            <li class="bg-white/5 rounded-lg p-4 hover:bg-white/10 transition-all">
              <h3 class="text-white font-semibold mb-2 flex items-center gap-2">
                <span class="w-2 h-2 bg-pink-500 rounded-full"></span>
                Training
              </h3>
              <p class="text-white/80">The process of feeding data into the model to help it learn.</p>
            </li>
            <li class="bg-white/5 rounded-lg p-4 hover:bg-white/10 transition-all">
              <h3 class="text-white font-semibold mb-2 flex items-center gap-2">
                <span class="w-2 h-2 bg-green-500 rounded-full"></span>
                Prediction
              </h3>
              <p class="text-white/80">The outcome generated by the model after training.</p>
            </li>
          </ul>
        </div>

        <div class="bg-gradient-to-br from-black/50 to-blue-950/30 backdrop-blur-sm rounded-xl p-6 border border-white/10">
          <div class="flex items-center gap-3 mb-4">
            <div class="w-10 h-10 rounded-full bg-yellow-500/20 flex items-center justify-center">
              <span class="text-yellow-400 text-xl">💡</span>
            </div>
            <h3 class="text-xl font-semibold text-white">Example</h3>
          </div>
          <p class="text-white/80 bg-black/30 rounded-lg p-4 border border-white/5">
            A spam filter learns from past emails (data) to predict whether a new email is spam or not.
          </p>
        </div>

        <div class="mt-8 overflow-hidden rounded-xl border border-white/10">
          <img 
            src="/banner.jpg" 
            alt="Machine Learning Process" 
            class="w-full object-cover hover:scale-105 transition-transform duration-500"
          />
        </div>
      </div>
    `,
    },
    "ML & AI": {
      heading: "Machine Learning and Artificial Intelligence",
      content: `
      <div class="space-y-8">
        <div class="bg-gradient-to-r from-purple-500/10 via-indigo-500/10 to-blue-500/10 p-8 rounded-2xl backdrop-blur-sm border border-white/10">
          <p class="text-xl text-white/90 leading-relaxed">
            Artificial Intelligence (AI) refers to the simulation of human intelligence in machines that can perform tasks typically requiring human cognition. Machine Learning (ML) is a subfield of AI that uses data to enable computers to learn and improve over time without explicit programming.
          </p>
        </div>
        
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div class="bg-black/50 backdrop-blur-sm border border-white/10 rounded-xl p-6 hover:border-white/20 transition-all duration-300">
            <div class="flex items-center gap-3 mb-6">
              <div class="w-10 h-10 rounded-full bg-purple-500/20 flex items-center justify-center">
                <span class="text-purple-400 text-xl">🤖</span>
              </div>
              <h3 class="text-xl font-semibold text-white">AI Features</h3>
            </div>
            <ul class="space-y-4">
              <li class="flex items-center gap-3 text-white/80 group">
                <span class="w-2 h-2 bg-gradient-to-r from-purple-500 to-purple-600 rounded-full"></span>
                <span class="group-hover:text-white transition-colors">Decision Making</span>
              </li>
              <li class="flex items-center gap-3 text-white/80 group">
                <span class="w-2 h-2 bg-gradient-to-r from-purple-500 to-purple-600 rounded-full"></span>
                <span class="group-hover:text-white transition-colors">Understanding Speech</span>
              </li>
            </ul>
          </div>

          <div class="bg-black/50 backdrop-blur-sm border border-white/10 rounded-xl p-6 hover:border-white/20 transition-all duration-300">
            <div class="flex items-center gap-3 mb-6">
              <div class="w-10 h-10 rounded-full bg-blue-500/20 flex items-center justify-center">
                <span class="text-blue-400 text-xl">🧠</span>
              </div>
              <h3 class="text-xl font-semibold text-white">ML Features</h3>
            </div>
            <ul class="space-y-4">
              <li class="flex items-center gap-3 text-white/80 group">
                <span class="w-2 h-2 bg-gradient-to-r from-blue-500 to-blue-600 rounded-full"></span>
                <span class="group-hover:text-white transition-colors">Image Recognition</span>
              </li>
              <li class="flex items-center gap-3 text-white/80 group">
                <span class="w-2 h-2 bg-gradient-to-r from-blue-500 to-blue-600 rounded-full"></span>
                <span class="group-hover:text-white transition-colors">Recommendations</span>
              </li>
            </ul>
          </div>
        </div>

        <div class="bg-gradient-to-br from-black/50 to-purple-950/30 backdrop-blur-sm rounded-xl p-6 border border-white/10">
          <div class="flex items-center gap-3 mb-4">
            <div class="w-10 h-10 rounded-full bg-green-500/20 flex items-center justify-center">
              <span class="text-green-400 text-xl">💡</span>
            </div>
            <h3 class="text-xl font-semibold text-white">Real-World Example</h3>
          </div>
          <p class="text-white/80 bg-black/30 rounded-lg p-4 border border-white/5">
            AI powers virtual assistants like Siri for natural conversations, while ML helps music services suggest songs based on your listening history.
          </p>
        </div>

        <div class="mt-8 overflow-hidden rounded-xl border border-white/10 group">
          <img 
            src="/banner.jpg" 
            alt="AI and ML Comparison" 
            class="w-full object-cover group-hover:scale-105 transition-transform duration-500"
          />
        </div>
      </div>
    `,
    },
    "ML Languages": {
      heading: "Machine Learning Languages",
      content: `
      <div class="space-y-8">
        <div class="bg-gradient-to-r from-blue-500/10 via-cyan-500/10 to-teal-500/10 p-8 rounded-2xl backdrop-blur-sm border border-white/10">
          <p class="text-xl text-white/90 leading-relaxed">
            Different programming languages offer unique advantages for Machine Learning, from data manipulation to model training and deployment.
          </p>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div class="bg-black/50 backdrop-blur-sm border border-white/10 rounded-xl p-6 hover:border-white/20 transition-all duration-300 group">
            <div class="flex items-center gap-3 mb-6">
              <div class="w-10 h-10 rounded-full bg-blue-500/20 flex items-center justify-center group-hover:scale-110 transition-transform">
                <span class="text-blue-400 text-xl">🐍</span>
              </div>
              <h3 class="text-xl font-semibold text-white">Python</h3>
            </div>
            <p class="text-white/80 mb-4">The most popular language for ML, known for its simplicity and vast ecosystem.</p>
            <div class="space-y-2">
              <div class="bg-white/5 rounded-lg px-3 py-1 text-sm text-white/60">TensorFlow</div>
              <div class="bg-white/5 rounded-lg px-3 py-1 text-sm text-white/60">Scikit-learn</div>
              <div class="bg-white/5 rounded-lg px-3 py-1 text-sm text-white/60">Keras</div>
            </div>
          </div>

          <div class="bg-black/50 backdrop-blur-sm border border-white/10 rounded-xl p-6 hover:border-white/20 transition-all duration-300 group">
            <div class="flex items-center gap-3 mb-6">
              <div class="w-10 h-10 rounded-full bg-cyan-500/20 flex items-center justify-center group-hover:scale-110 transition-transform">
                <span class="text-cyan-400 text-xl">📊</span>
              </div>
              <h3 class="text-xl font-semibold text-white">R</h3>
            </div>
            <p class="text-white/80 mb-4">Primarily used for statistical analysis and data visualization.</p>
            <div class="space-y-2">
              <div class="bg-white/5 rounded-lg px-3 py-1 text-sm text-white/60">ggplot2</div>
              <div class="bg-white/5 rounded-lg px-3 py-1 text-sm text-white/60">caret</div>
              <div class="bg-white/5 rounded-lg px-3 py-1 text-sm text-white/60">tidyverse</div>
            </div>
          </div>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div class="bg-black/50 backdrop-blur-sm border border-white/10 rounded-xl p-6 hover:border-white/20 transition-all duration-300 group">
            <div class="flex items-center gap-3 mb-6">
              <div class="w-10 h-10 rounded-full bg-purple-500/20 flex items-center justify-center group-hover:scale-110 transition-transform">
                <span class="text-purple-400 text-xl">⚡</span>
              </div>
              <h3 class="text-xl font-semibold text-white">Julia</h3>
            </div>
            <p class="text-white/80">High-performance computing for large datasets and complex calculations.</p>
          </div>

          <div class="bg-black/50 backdrop-blur-sm border border-white/10 rounded-xl p-6 hover:border-white/20 transition-all duration-300 group">
            <div class="flex items-center gap-3 mb-6">
              <div class="w-10 h-10 rounded-full bg-orange-500/20 flex items-center justify-center group-hover:scale-110 transition-transform">
                <span class="text-orange-400 text-xl">🔬</span>
              </div>
              <h3 class="text-xl font-semibold text-white">MATLAB</h3>
            </div>
            <p class="text-white/80">Popular in academia for numerical computing and algorithm development.</p>
          </div>
        </div>

        <div class="mt-8 overflow-hidden rounded-xl border border-white/10 relative group">
          <div class="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent z-10"></div>
          <img 
            src="/banner.jpg" 
            alt="Programming Languages for ML" 
            class="w-full object-cover group-hover:scale-105 transition-transform duration-500"
          />
        </div>
      </div>
    `,
    },
    "ML JavaScript": {
      heading: "Machine Learning with JavaScript",
      content: `
        <div class="space-y-8">
          <div class="bg-gradient-to-r from-yellow-500/10 via-orange-500/10 to-red-500/10 p-8 rounded-2xl backdrop-blur-sm border border-white/10">
            <p class="text-xl text-white/90 leading-relaxed">
              JavaScript brings Machine Learning to the web browser, enabling real-time, interactive ML applications without backend dependencies.
            </p>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div class="bg-black/50 backdrop-blur-sm border border-white/10 rounded-xl p-6 hover:border-white/20 transition-all duration-300 group">
              <div class="flex items-center gap-3 mb-6">
                <div class="w-10 h-10 rounded-full bg-yellow-500/20 flex items-center justify-center group-hover:scale-110 transition-transform">
                  <span class="text-yellow-400 text-xl">⚡</span>
                </div>
                <h3 class="text-xl font-semibold text-white">Real-time Processing</h3>
              </div>
              <p class="text-white/80">ML models run instantly in the browser for immediate results.</p>
            </div>

            <div class="bg-black/50 backdrop-blur-sm border border-white/10 rounded-xl p-6 hover:border-white/20 transition-all duration-300 group">
              <div class="flex items-center gap-3 mb-6">
                <div class="w-10 h-10 rounded-full bg-orange-500/20 flex items-center justify-center group-hover:scale-110 transition-transform">
                  <span class="text-orange-400 text-xl">🌐</span>
                </div>
                <h3 class="text-xl font-semibold text-white">Web Integration</h3>
              </div>
              <p class="text-white/80">Seamlessly integrate ML features into web applications.</p>
            </div>

            <div class="bg-black/50 backdrop-blur-sm border border-white/10 rounded-xl p-6 hover:border-white/20 transition-all duration-300 group">
              <div class="flex items-center gap-3 mb-6">
                <div class="w-10 h-10 rounded-full bg-red-500/20 flex items-center justify-center group-hover:scale-110 transition-transform">
                  <span class="text-red-400 text-xl">🚀</span>
                </div>
                <h3 class="text-xl font-semibold text-white">Client-Side ML</h3>
              </div>
              <p class="text-white/80">No backend required, reducing server load and costs.</p>
            </div>
          </div>

          <div class="bg-black/50 backdrop-blur-sm border border-white/10 rounded-xl p-6 hover:border-white/20 transition-all duration-300">
            <div class="flex items-center gap-3 mb-6">
              <div class="w-10 h-10 rounded-full bg-blue-500/20 flex items-center justify-center">
                <span class="text-blue-400 text-xl">📚</span>
              </div>
              <h3 class="text-xl font-semibold text-white">Popular Libraries</h3>
            </div>
            <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div class="bg-white/5 rounded-lg p-4 text-center hover:bg-white/10 transition-colors">
                <span class="text-white/80">TensorFlow.js</span>
              </div>
              <div class="bg-white/5 rounded-lg p-4 text-center hover:bg-white/10 transition-colors">
                <span class="text-white/80">Brain.js</span>
              </div>
              <div class="bg-white/5 rounded-lg p-4 text-center hover:bg-white/10 transition-colors">
                <span class="text-white/80">ML5.js</span>
              </div>
              <div class="bg-white/5 rounded-lg p-4 text-center hover:bg-white/10 transition-colors">
                <span class="text-white/80">Synaptic</span>
              </div>
            </div>
          </div>

          <div class="mt-8 overflow-hidden rounded-xl border border-white/10 group relative">
            <div class="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent z-10"></div>
            <img 
              src="/banner.jpg" 
              alt="JavaScript ML Development" 
              class="w-full object-cover group-hover:scale-105 transition-transform duration-500"
            />
          </div>
        </div>
      `,
    },
    "ML Examples": {
      heading: "Examples of Machine Learning",
      content: `
        <div class="space-y-8">
          <div class="bg-gradient-to-r from-green-500/10 via-emerald-500/10 to-teal-500/10 p-8 rounded-2xl backdrop-blur-sm border border-white/10">
            <p class="text-xl text-white/90 leading-relaxed">
              Machine Learning powers many of the technologies we use daily, from content recommendations to image recognition.
            </p>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div class="bg-black/50 backdrop-blur-sm border border-white/10 rounded-xl p-6 hover:border-white/20 transition-all duration-300 group">
              <div class="flex items-center gap-3 mb-6">
                <div class="w-10 h-10 rounded-full bg-green-500/20 flex items-center justify-center group-hover:scale-110 transition-transform">
                  <span class="text-green-400 text-xl">🎯</span>
                </div>
                <h3 class="text-xl font-semibold text-white">Recommendations</h3>
              </div>
              <ul class="space-y-3">
                <li class="flex items-center gap-2 text-white/80">
                  <span class="w-1.5 h-1.5 bg-green-500 rounded-full"></span>
                  Netflix Shows
                </li>
                <li class="flex items-center gap-2 text-white/80">
                  <span class="w-1.5 h-1.5 bg-green-500 rounded-full"></span>
                  Spotify Playlists
                </li>
                <li class="flex items-center gap-2 text-white/80">
                  <span class="w-1.5 h-1.5 bg-green-500 rounded-full"></span>
                  Amazon Products
                </li>
              </ul>
            </div>

            <div class="bg-black/50 backdrop-blur-sm border border-white/10 rounded-xl p-6 hover:border-white/20 transition-all duration-300 group">
              <div class="flex items-center gap-3 mb-6">
                <div class="w-10 h-10 rounded-full bg-emerald-500/20 flex items-center justify-center group-hover:scale-110 transition-transform">
                  <span class="text-emerald-400 text-xl">👁️</span>
                </div>
                <h3 class="text-xl font-semibold text-white">Computer Vision</h3>
              </div>
              <ul class="space-y-3">
                <li class="flex items-center gap-2 text-white/80">
                  <span class="w-1.5 h-1.5 bg-emerald-500 rounded-full"></span>
                  Face Recognition
                </li>
                <li class="flex items-center gap-2 text-white/80">
                  <span class="w-1.5 h-1.5 bg-emerald-500 rounded-full"></span>
                  Object Detection
                </li>
                <li class="flex items-center gap-2 text-white/80">
                  <span class="w-1.5 h-1.5 bg-emerald-500 rounded-full"></span>
                  Medical Imaging
                </li>
              </ul>
            </div>

            <div class="bg-black/50 backdrop-blur-sm border border-white/10 rounded-xl p-6 hover:border-white/20 transition-all duration-300 group">
              <div class="flex items-center gap-3 mb-6">
                <div class="w-10 h-10 rounded-full bg-teal-500/20 flex items-center justify-center group-hover:scale-110 transition-transform">
                  <span class="text-teal-400 text-xl">💬</span>
                </div>
                <h3 class="text-xl font-semibold text-white">NLP</h3>
              </div>
              <ul class="space-y-3">
                <li class="flex items-center gap-2 text-white/80">
                  <span class="w-1.5 h-1.5 bg-teal-500 rounded-full"></span>
                  Chatbots
                </li>
                <li class="flex items-center gap-2 text-white/80">
                  <span class="w-1.5 h-1.5 bg-teal-500 rounded-full"></span>
                  Translation
                </li>
                <li class="flex items-center gap-2 text-white/80">
                  <span class="w-1.5 h-1.5 bg-teal-500 rounded-full"></span>
                  Text Analysis
                </li>
              </ul>
            </div>
          </div>

          <div class="bg-gradient-to-br from-black/50 to-green-950/30 backdrop-blur-sm rounded-xl p-6 border border-white/10">
            <div class="flex items-center gap-3 mb-4">
              <div class="w-10 h-10 rounded-full bg-blue-500/20 flex items-center justify-center">
                <span class="text-blue-400 text-xl">💡</span>
              </div>
              <h3 class="text-xl font-semibold text-white">Real-World Example</h3>
            </div>
            <p class="text-white/80 bg-black/30 rounded-lg p-4 border border-white/5">
              Google Photos uses ML to automatically organize your photos into albums based on faces, places, and events it recognizes in your images.
            </p>
          </div>
        </div>
      `,
    },
    "ML Linear Graphs": {
      heading: "Machine Learning with Linear Graphs",
      content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Linear graphs are a crucial component in Machine Learning, used primarily in regression tasks to represent relationships between variables. Below are some examples where ML models utilize linear graphs:
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">Applications of Linear Graphs in ML</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Linear Regression:</strong> This is one of the simplest and most common algorithms in machine learning, where a straight line is used to model the relationship between independent and dependent variables. It's often used for predicting continuous values like house prices or sales trends.</li>
            <li><strong>Trend Prediction:</strong> Linear graphs are used to predict future trends in data, such as stock market prices, weather forecasting, or demand forecasting, based on historical data points.</li>
            <li><strong>Optimizing Performance:</strong> In optimization problems, linear graphs help identify the best solution that satisfies a set of constraints. This is commonly used in logistics, resource allocation, and production planning.</li>
          </ul>
        </div>

        <p class="text-lg text-gray-800">
          **Example**: In a linear regression model, a linear graph is used to represent the relationship between a dataset's features (independent variables) and the target variable (dependent variable), allowing us to make predictions.
        </p>

        <div class="mt-6">
          <img src="/banner.jpg" alt="Machine Learning Linear Graph" class="w-full rounded-lg shadow-md" />
        </div>
      </div>
    `,
    },

    "ML Scatter Plots": {
      heading: "ML Scatter Plots",
      content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Scatter plots are widely used in Machine Learning to visualize and analyze relationships between two continuous variables. They are essential tools for understanding correlations, trends, and outliers in datasets. Here are some key use cases of scatter plots in machine learning:
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">Scatter Plot Use Cases in ML</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Data Visualization:</strong> Scatter plots help in visualizing the relationship between two variables in a dataset. For example, scatter plots can be used to show how the number of hours studied relates to exam scores.</li>
            <li><strong>Identifying Trends and Patterns:</strong> By plotting data points on a scatter plot, ML models can easily identify patterns, such as positive or negative correlations between variables, which can be used to develop predictive models.</li>
            <li><strong>Outlier Detection:</strong> Scatter plots can help identify anomalies or outliers in data, which might indicate errors or exceptional cases that need to be treated differently in model training.</li>
          </ul>
        </div>

        <p class="text-lg text-gray-800">
          **Example**: In a supervised learning task like linear regression, scatter plots are often used to visualize the relationship between the independent variable (e.g., hours studied) and the dependent variable (e.g., exam scores), making it easier to see the linear trend.
        </p>

        <div class="mt-6">
          <img src="/banner.jpg" alt="Scatter Plot Example" class="w-full rounded-lg shadow-md" />
        </div>
      </div>
    `,
    },
    "ML Perceptrons": {
    heading: "Understanding Perceptrons in Machine Learning",
    content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          A perceptron is the simplest form of a neural network used for binary classification tasks. It takes inputs, processes them using weights, and produces an output based on an activation function.
        </p>
        
        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">How It Works</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Inputs:</strong> Features of the data, e.g., numbers or categories.</li>
            <li><strong>Weights:</strong> Each input has an associated weight to signify importance.</li>
            <li><strong>Activation:</strong> A function that determines the final output.</li>
          </ul>
        </div>

        <div class="mt-6">
          <pre class="bg-black text-white p-4 rounded-lg">
            <code>
// Example: Simple Perceptron
inputs = [1, 0];
weights = [0.5, -0.5];
bias = 0.2;
output = inputs[0] * weights[0] + inputs[1] * weights[1] + bias;
console.log(output); // Result depends on inputs and weights
            </code>
          </pre>
        </div>
      </div>
    `,
  },
  "ML Recognition": {
    heading: "Machine Learning for Pattern Recognition",
    content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Pattern recognition is the ability of machines to identify and classify patterns in data. For example, recognizing faces in photos or classifying emails as spam.
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">Common Applications</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Face Recognition:</strong> Identifying individuals in images.</li>
            <li><strong>Speech Recognition:</strong> Converting spoken words to text.</li>
            <li><strong>Handwriting Recognition:</strong> Digitizing handwritten notes.</li>
          </ul>
        </div>

        <p class="text-lg text-gray-800">
          **Example**: A camera app that detects your face and unlocks your phone.
        </p>
      </div>
    `,
  },
  "ML Training": {
    heading: "Training Models in Machine Learning",
    content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Training a model involves feeding it data to help it learn and improve. This is like teaching a student with examples so they can solve problems in the future.
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">Steps in Training</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Prepare Data:</strong> Organize and clean the dataset.</li>
            <li><strong>Initialize Model:</strong> Set up the basic framework.</li>
            <li><strong>Train:</strong> Use algorithms like Gradient Descent to optimize performance.</li>
          </ul>
        </div>

        <div class="mt-6">
          <pre class="bg-black text-white p-4 rounded-lg">
            <code>
// Example: Training a Model
const trainingData = [{input: [0, 0], output: 0}, {input: [1, 1], output: 1}];
let weights = [0.5, 0.5];
function train(data, weights) {
  data.forEach(({input, output}) => {
    let prediction = input[0] * weights[0] + input[1] * weights[1];
    // Update weights based on error
    weights[0] += 0.1 * (output - prediction) * input[0];
    weights[1] += 0.1 * (output - prediction) * input[1];
  });
}
train(trainingData, weights);
            </code>
          </pre>
        </div>
      </div>
    `,
  },
  "ML Testing": {
    heading: "Testing Machine Learning Models",
    content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Testing a machine learning model involves evaluating its performance on unseen data to ensure it generalizes well.
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">Testing Metrics</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Accuracy:</strong> Percentage of correct predictions.</li>
            <li><strong>Precision:</strong> How many predicted positives are correct?</li>
            <li><strong>Recall:</strong> How many actual positives were correctly predicted?</li>
          </ul>
        </div>
      </div>
    `,
  },
  "ML Learning": {
    heading: "Machine Learning Learning",
    content: `
    <div class="space-y-6">
      <p class="text-lg text-gray-800">
        Machine Learning (ML) is a field of Artificial Intelligence (AI) that focuses on developing algorithms that allow computers to learn from and make decisions based on data.
      </p>
    </div>
  `,
  },
  "ML Terminology": {
    heading: "Machine Learning Terminology",
    content: `
    <div class="space-y-6">
      <p class="text-lg text-gray-800">
        Understanding the key terms in Machine Learning is crucial for grasping the concepts and techniques used in the field.
      </p>
    </div>
  `,
  },
  "ML Data": {
    heading: "Machine Learning Data",
    content: `
    <div class="space-y-6">
      <p class="text-lg text-gray-800">
        Data is the foundation of Machine Learning. It is used to train models and make predictions.
      </p>
    </div>
  `,
  },
  "ML Clustering": {
    heading: "What is Clustering in Machine Learning?",
    content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Clustering is the process of grouping data points so that points in the same group are more similar to each other than to points in other groups.
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">Example Algorithms</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>K-Means:</strong> Groups data into 'k' clusters.</li>
            <li><strong>Hierarchical Clustering:</strong> Builds a hierarchy of clusters.</li>
          </ul>
        </div>
      </div>
    `,
  },
  "ML Regressions": {
    heading: "Working on Regressions Page.",
    content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Working on Regressions Page.
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800"></h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong></strong></li>
            <li><strong></strong></li>
          </ul>
        </div>
      </div>
    `,
  },
  "ML Deep Learning": {
    heading: "Working on Deep Learning Page.",
    content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Working on Learning Page.
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800"></h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong></strong></li>
            <li><strong></strong></li>
          </ul>
        </div>
      </div>
    `,
  },
  "ML Brain.js": {
    heading: "Working on ML Brain.js Page.",
    content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Working on ML Brain.js Page.
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800"></h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong></strong></li>
            <li><strong></strong></li>
          </ul>
        </div>
      </div>
    `,
  },
};
