export type TopicKey = "What is ML?" | "ML & AI" | "ML Languages" | "ML JavaScript" | "ML Examples";

export const mlTopics: Record<TopicKey, { heading: string; content: string }> = {
  "What is ML?": {
    heading: "What is Machine Learning?",
    content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Machine Learning (ML) is a field of Artificial Intelligence (AI) that focuses on developing algorithms that allow computers to learn from and make decisions based on data. Instead of following explicit instructions, a machine can improve its performance over time by identifying patterns and making data-driven predictions.
        </p>
        
        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">Key Components of Machine Learning</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Data:</strong> The raw information that the machine learns from.</li>
            <li><strong>Model:</strong> A mathematical representation of a system that the machine uses to make predictions.</li>
            <li><strong>Training:</strong> The process of feeding data into the model to help it learn.</li>
            <li><strong>Prediction:</strong> The outcome generated by the model after training.</li>
          </ul>
        </div>

        <p class="text-lg text-gray-800">
          **Example**: A spam filter learns from past emails (data) to predict whether a new email is spam or not.
        </p>

        <div class="mt-6">
          <img src="/banner.jpg" alt="Machine Learning Process" class="w-full rounded-lg shadow-md" />
        </div>
      </div>
    `
  },
  "ML & AI": {
    heading: "Machine Learning and Artificial Intelligence",
    content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Artificial Intelligence (AI) refers to the simulation of human intelligence in machines that can perform tasks typically requiring human cognition, such as learning, reasoning, and problem-solving. Machine Learning (ML) is a subfield of AI that uses data to enable computers to learn and improve over time without explicit programming.
        </p>
        
        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">Difference between AI and ML</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>AI:</strong> Includes various techniques to build systems capable of performing tasks that require human-like intelligence (e.g., decision making, understanding speech).</li>
            <li><strong>ML:</strong> Refers to systems that learn from data to predict outcomes or make decisions (e.g., image recognition, recommendations).</li>
          </ul>
        </div>

        <p class="text-lg text-gray-800">
          **Example**: AI could be used in a virtual assistant like Siri, while ML might be used to suggest music based on your listening history.
        </p>

        <div class="mt-6">
          <img src="/banner.jpg" alt="Machine Learning Process" class="w-full rounded-lg shadow-md" />
        </div>
      </div>
    `
  },
  "ML Languages": {
    heading: "Machine Learning Languages",
    content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Certain programming languages are better suited for Machine Learning due to their support for data manipulation, model training, and deep learning frameworks.
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">Popular ML Languages</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Python:</strong> The most popular language for ML, known for its simplicity and a vast ecosystem of libraries such as TensorFlow, Scikit-learn, and Keras.</li>
            <li><strong>R:</strong> Primarily used for statistical analysis and data visualization, R has excellent support for data science and ML libraries.</li>
            <li><strong>Julia:</strong> A newer language gaining traction due to its high-performance capabilities for numerical computing, especially for large datasets.</li>
            <li><strong>MATLAB:</strong> Often used in academia for numerical computing and machine learning algorithms.</li>
          </ul>
        </div>

        <div class="mt-6">
          <img src="/banner.jpg" alt="Machine Learning Process" class="w-full rounded-lg shadow-md" />
        </div>
      </div>
    `
  },
  "ML JavaScript": {
    heading: "Machine Learning with JavaScript",
    content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          JavaScript is often overlooked for Machine Learning, but it is an excellent language for developing interactive web-based ML applications. Libraries like <strong>TensorFlow.js</strong> allow developers to run models directly in the browser without the need for backend processing.
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">Advantages of ML with JavaScript</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Real-time Processing:</strong> ML models can run in real-time on the client side in the browser.</li>
            <li><strong>Web Integration:</strong> Seamlessly integrates with web applications to create interactive ML-driven features.</li>
            <li><strong>No Backend Needed:</strong> Models can be trained and used entirely within the browser, reducing server load.</li>
          </ul>
        </div>

        <p class="text-lg text-gray-800">
          **Example**: A web app that predicts user behavior or provides interactive data analysis in real-time using JavaScript.
        </p>

        <div class="mt-6">
          <img src="/banner.jpg" alt="Machine Learning Process" class="w-full rounded-lg shadow-md" />
        </div>
      </div>
    `
  },
  "ML Examples": {
    heading: "Examples of Machine Learning",
    content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Machine Learning is integrated into many technologies we use every day. Here are a few examples:
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">ML Use Cases</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Recommendation Systems:</strong> Platforms like Netflix, YouTube, and Amazon use ML algorithms to recommend movies, shows, or products based on past interactions.</li>
            <li><strong>Image Recognition:</strong> ML is used in facial recognition, object detection, and medical image analysis.</li>
            <li><strong>Natural Language Processing (NLP):</strong> NLP helps machines understand and process human language, enabling speech-to-text, sentiment analysis, and chatbots.</li>
          </ul>
        </div>

        <p class="text-lg text-gray-800">
          **Example**: Google Photos uses ML to automatically categorize your photos into albums based on content, such as people, locations, and events.
        </p>

        <div class="mt-6">
          <img src="/banner.jpg" alt="Machine Learning Process" class="w-full rounded-lg shadow-md" />
        </div>
      </div>
    `
  }
};
