export type TopicKey =
  | "What is ML?"
  | "ML & AI"
  | "ML Languages"
  | "ML JavaScript"
  | "ML Examples"
  | "ML Linear Graphs"
  | "ML Scatter Plots"
  | "ML Perceptrons"
  | "ML Recognition"
  | "ML Training"
  | "ML Testing"
  | "ML Learning"
  | "ML Terminology"
  | "ML Data"
  | "ML Clustering"
  | "ML Regressions"
  | "ML Deep Learning"
  | "ML Brain.js";

export const mlTopics: Record<TopicKey, { heading: string; content: string }> =
  {
    "What is ML?": {
      heading: "What is Machine Learning?",
      content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Machine Learning (ML) is a field of Artificial Intelligence (AI) that focuses on developing algorithms that allow computers to learn from and make decisions based on data. Instead of following explicit instructions, a machine can improve its performance over time by identifying patterns and making data-driven predictions.
        </p>
        
        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">Key Components of Machine Learning</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Data:</strong> The raw information that the machine learns from.</li>
            <li><strong>Model:</strong> A mathematical representation of a system that the machine uses to make predictions.</li>
            <li><strong>Training:</strong> The process of feeding data into the model to help it learn.</li>
            <li><strong>Prediction:</strong> The outcome generated by the model after training.</li>
          </ul>
        </div>

        <p class="text-lg text-gray-800">
          **Example**: A spam filter learns from past emails (data) to predict whether a new email is spam or not.
        </p>

        <div class="mt-6">
          <img src="/banner.jpg" alt="Machine Learning Process" class="w-full rounded-lg shadow-md" />
        </div>
      </div>
    `,
    },
    "ML & AI": {
      heading: "Machine Learning and Artificial Intelligence",
      content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Artificial Intelligence (AI) refers to the simulation of human intelligence in machines that can perform tasks typically requiring human cognition, such as learning, reasoning, and problem-solving. Machine Learning (ML) is a subfield of AI that uses data to enable computers to learn and improve over time without explicit programming.
        </p>
        
        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">Difference between AI and ML</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>AI:</strong> Includes various techniques to build systems capable of performing tasks that require human-like intelligence (e.g., decision making, understanding speech).</li>
            <li><strong>ML:</strong> Refers to systems that learn from data to predict outcomes or make decisions (e.g., image recognition, recommendations).</li>
          </ul>
        </div>

        <p class="text-lg text-gray-800">
          **Example**: AI could be used in a virtual assistant like Siri, while ML might be used to suggest music based on your listening history.
        </p>

        <div class="mt-6">
          <img src="/banner.jpg" alt="Machine Learning Process" class="w-full rounded-lg shadow-md" />
        </div>
      </div>
    `,
    },
    "ML Languages": {
      heading: "Machine Learning Languages",
      content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Certain programming languages are better suited for Machine Learning due to their support for data manipulation, model training, and deep learning frameworks.
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">Popular ML Languages</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Python:</strong> The most popular language for ML, known for its simplicity and a vast ecosystem of libraries such as TensorFlow, Scikit-learn, and Keras.</li>
            <li><strong>R:</strong> Primarily used for statistical analysis and data visualization, R has excellent support for data science and ML libraries.</li>
            <li><strong>Julia:</strong> A newer language gaining traction due to its high-performance capabilities for numerical computing, especially for large datasets.</li>
            <li><strong>MATLAB:</strong> Often used in academia for numerical computing and machine learning algorithms.</li>
          </ul>
        </div>

        <div class="mt-6">
          <img src="/banner.jpg" alt="Machine Learning Process" class="w-full rounded-lg shadow-md" />
        </div>
      </div>
    `,
    },
    "ML JavaScript": {
      heading: "Machine Learning with JavaScript",
      content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          JavaScript is often overlooked for Machine Learning, but it is an excellent language for developing interactive web-based ML applications. Libraries like <strong>TensorFlow.js</strong> allow developers to run models directly in the browser without the need for backend processing.
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">Advantages of ML with JavaScript</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Real-time Processing:</strong> ML models can run in real-time on the client side in the browser.</li>
            <li><strong>Web Integration:</strong> Seamlessly integrates with web applications to create interactive ML-driven features.</li>
            <li><strong>No Backend Needed:</strong> Models can be trained and used entirely within the browser, reducing server load.</li>
          </ul>
        </div>

        <p class="text-lg text-gray-800">
          **Example**: A web app that predicts user behavior or provides interactive data analysis in real-time using JavaScript.
        </p>

        <div class="mt-6">
          <img src="/banner.jpg" alt="Machine Learning Process" class="w-full rounded-lg shadow-md" />
        </div>
      </div>
    `,
    },
    "ML Examples": {
      heading: "Examples of Machine Learning",
      content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Machine Learning is integrated into many technologies we use every day. Here are a few examples:
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">ML Use Cases</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Recommendation Systems:</strong> Platforms like Netflix, YouTube, and Amazon use ML algorithms to recommend movies, shows, or products based on past interactions.</li>
            <li><strong>Image Recognition:</strong> ML is used in facial recognition, object detection, and medical image analysis.</li>
            <li><strong>Natural Language Processing (NLP):</strong> NLP helps machines understand and process human language, enabling speech-to-text, sentiment analysis, and chatbots.</li>
          </ul>
        </div>

        <p class="text-lg text-gray-800">
          **Example**: Google Photos uses ML to automatically categorize your photos into albums based on content, such as people, locations, and events.
        </p>

        <div class="mt-6">
          <img src="/banner.jpg" alt="Machine Learning Process" class="w-full rounded-lg shadow-md" />
        </div>
      </div>
    `,
    },
    "ML Linear Graphs": {
      heading: "Machine Learning with Linear Graphs",
      content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Linear graphs are a crucial component in Machine Learning, used primarily in regression tasks to represent relationships between variables. Below are some examples where ML models utilize linear graphs:
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">Applications of Linear Graphs in ML</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Linear Regression:</strong> This is one of the simplest and most common algorithms in machine learning, where a straight line is used to model the relationship between independent and dependent variables. It's often used for predicting continuous values like house prices or sales trends.</li>
            <li><strong>Trend Prediction:</strong> Linear graphs are used to predict future trends in data, such as stock market prices, weather forecasting, or demand forecasting, based on historical data points.</li>
            <li><strong>Optimizing Performance:</strong> In optimization problems, linear graphs help identify the best solution that satisfies a set of constraints. This is commonly used in logistics, resource allocation, and production planning.</li>
          </ul>
        </div>

        <p class="text-lg text-gray-800">
          **Example**: In a linear regression model, a linear graph is used to represent the relationship between a dataset's features (independent variables) and the target variable (dependent variable), allowing us to make predictions.
        </p>

        <div class="mt-6">
          <img src="/banner.jpg" alt="Machine Learning Linear Graph" class="w-full rounded-lg shadow-md" />
        </div>
      </div>
    `,
    },

    "ML Scatter Plots": {
      heading: "ML Scatter Plots",
      content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Scatter plots are widely used in Machine Learning to visualize and analyze relationships between two continuous variables. They are essential tools for understanding correlations, trends, and outliers in datasets. Here are some key use cases of scatter plots in machine learning:
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">Scatter Plot Use Cases in ML</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Data Visualization:</strong> Scatter plots help in visualizing the relationship between two variables in a dataset. For example, scatter plots can be used to show how the number of hours studied relates to exam scores.</li>
            <li><strong>Identifying Trends and Patterns:</strong> By plotting data points on a scatter plot, ML models can easily identify patterns, such as positive or negative correlations between variables, which can be used to develop predictive models.</li>
            <li><strong>Outlier Detection:</strong> Scatter plots can help identify anomalies or outliers in data, which might indicate errors or exceptional cases that need to be treated differently in model training.</li>
          </ul>
        </div>

        <p class="text-lg text-gray-800">
          **Example**: In a supervised learning task like linear regression, scatter plots are often used to visualize the relationship between the independent variable (e.g., hours studied) and the dependent variable (e.g., exam scores), making it easier to see the linear trend.
        </p>

        <div class="mt-6">
          <img src="/banner.jpg" alt="Scatter Plot Example" class="w-full rounded-lg shadow-md" />
        </div>
      </div>
    `,
    },
    "ML Perceptrons": {
    heading: "Understanding Perceptrons in Machine Learning",
    content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          A perceptron is the simplest form of a neural network used for binary classification tasks. It takes inputs, processes them using weights, and produces an output based on an activation function.
        </p>
        
        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">How It Works</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Inputs:</strong> Features of the data, e.g., numbers or categories.</li>
            <li><strong>Weights:</strong> Each input has an associated weight to signify importance.</li>
            <li><strong>Activation:</strong> A function that determines the final output.</li>
          </ul>
        </div>

        <div class="mt-6">
          <pre class="bg-black text-white p-4 rounded-lg">
            <code>
// Example: Simple Perceptron
inputs = [1, 0];
weights = [0.5, -0.5];
bias = 0.2;
output = inputs[0] * weights[0] + inputs[1] * weights[1] + bias;
console.log(output); // Result depends on inputs and weights
            </code>
          </pre>
        </div>
      </div>
    `,
  },
  "ML Recognition": {
    heading: "Machine Learning for Pattern Recognition",
    content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Pattern recognition is the ability of machines to identify and classify patterns in data. For example, recognizing faces in photos or classifying emails as spam.
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">Common Applications</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Face Recognition:</strong> Identifying individuals in images.</li>
            <li><strong>Speech Recognition:</strong> Converting spoken words to text.</li>
            <li><strong>Handwriting Recognition:</strong> Digitizing handwritten notes.</li>
          </ul>
        </div>

        <p class="text-lg text-gray-800">
          **Example**: A camera app that detects your face and unlocks your phone.
        </p>
      </div>
    `,
  },
  "ML Training": {
    heading: "Training Models in Machine Learning",
    content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Training a model involves feeding it data to help it learn and improve. This is like teaching a student with examples so they can solve problems in the future.
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">Steps in Training</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Prepare Data:</strong> Organize and clean the dataset.</li>
            <li><strong>Initialize Model:</strong> Set up the basic framework.</li>
            <li><strong>Train:</strong> Use algorithms like Gradient Descent to optimize performance.</li>
          </ul>
        </div>

        <div class="mt-6">
          <pre class="bg-black text-white p-4 rounded-lg">
            <code>
// Example: Training a Model
const trainingData = [{input: [0, 0], output: 0}, {input: [1, 1], output: 1}];
let weights = [0.5, 0.5];
function train(data, weights) {
  data.forEach(({input, output}) => {
    let prediction = input[0] * weights[0] + input[1] * weights[1];
    // Update weights based on error
    weights[0] += 0.1 * (output - prediction) * input[0];
    weights[1] += 0.1 * (output - prediction) * input[1];
  });
}
train(trainingData, weights);
            </code>
          </pre>
        </div>
      </div>
    `,
  },
  "ML Testing": {
    heading: "Testing Machine Learning Models",
    content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Testing a machine learning model involves evaluating its performance on unseen data to ensure it generalizes well.
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">Testing Metrics</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Accuracy:</strong> Percentage of correct predictions.</li>
            <li><strong>Precision:</strong> How many predicted positives are correct?</li>
            <li><strong>Recall:</strong> How many actual positives were correctly predicted?</li>
          </ul>
        </div>
      </div>
    `,
  },
  "ML Learning": {
    heading: "Machine Learning Learning",
    content: `
    <div class="space-y-6">
      <p class="text-lg text-gray-800">
        Machine Learning (ML) is a field of Artificial Intelligence (AI) that focuses on developing algorithms that allow computers to learn from and make decisions based on data.
      </p>
    </div>
  `,
  },
  "ML Terminology": {
    heading: "Machine Learning Terminology",
    content: `
    <div class="space-y-6">
      <p class="text-lg text-gray-800">
        Understanding the key terms in Machine Learning is crucial for grasping the concepts and techniques used in the field.
      </p>
    </div>
  `,
  },
  "ML Data": {
    heading: "Machine Learning Data",
    content: `
    <div class="space-y-6">
      <p class="text-lg text-gray-800">
        Data is the foundation of Machine Learning. It is used to train models and make predictions.
      </p>
    </div>
  `,
  },
  "ML Clustering": {
    heading: "What is Clustering in Machine Learning?",
    content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Clustering is the process of grouping data points so that points in the same group are more similar to each other than to points in other groups.
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">Example Algorithms</h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>K-Means:</strong> Groups data into 'k' clusters.</li>
            <li><strong>Hierarchical Clustering:</strong> Builds a hierarchy of clusters.</li>
          </ul>
        </div>
      </div>
    `,
  },
  "ML Regressions": {
    heading: "Working on Regressions Page.",
    content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Working on Regressions Page.
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800"></h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong></strong></li>
            <li><strong></strong></li>
          </ul>
        </div>
      </div>
    `,
  },
  "ML Deep Learning": {
    heading: "Working on Deep Learning Page.",
    content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Working on Learning Page.
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800"></h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong></strong></li>
            <li><strong></strong></li>
          </ul>
        </div>
      </div>
    `,
  },
  "ML Brain.js": {
    heading: "Working on ML Brain.js Page.",
    content: `
      <div class="space-y-6">
        <p class="text-lg text-gray-800">
          Working on ML Brain.js Page.
        </p>

        <div class="bg-gray-50 p-4 rounded-lg shadow-lg space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800"></h2>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong></strong></li>
            <li><strong></strong></li>
          </ul>
        </div>
      </div>
    `,
  },
};
